# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from tests.services import greet_pb2 as tests_dot_services_dot_greet__pb2


class GreeterStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SayHello = channel.unary_unary(
                '/greet.v1.Greeter/SayHello',
                request_serializer=tests_dot_services_dot_greet__pb2.HelloRequest.SerializeToString,
                response_deserializer=tests_dot_services_dot_greet__pb2.HelloReply.FromString,
                )
        self.SecureSayHello = channel.unary_unary(
                '/greet.v1.Greeter/SecureSayHello',
                request_serializer=tests_dot_services_dot_greet__pb2.HelloRequest.SerializeToString,
                response_deserializer=tests_dot_services_dot_greet__pb2.HelloReply.FromString,
                )


class GreeterServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SayHello(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SecureSayHello(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GreeterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SayHello': grpc.unary_unary_rpc_method_handler(
                    servicer.SayHello,
                    request_deserializer=tests_dot_services_dot_greet__pb2.HelloRequest.FromString,
                    response_serializer=tests_dot_services_dot_greet__pb2.HelloReply.SerializeToString,
            ),
            'SecureSayHello': grpc.unary_unary_rpc_method_handler(
                    servicer.SecureSayHello,
                    request_deserializer=tests_dot_services_dot_greet__pb2.HelloRequest.FromString,
                    response_serializer=tests_dot_services_dot_greet__pb2.HelloReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'greet.v1.Greeter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Greeter(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SayHello(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/greet.v1.Greeter/SayHello',
            tests_dot_services_dot_greet__pb2.HelloRequest.SerializeToString,
            tests_dot_services_dot_greet__pb2.HelloReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SecureSayHello(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/greet.v1.Greeter/SecureSayHello',
            tests_dot_services_dot_greet__pb2.HelloRequest.SerializeToString,
            tests_dot_services_dot_greet__pb2.HelloReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
